[context.production]
  environment = { NODE_ENV = "production", NODE_VERSION = "16.0.0", JEKYLL_ENV = "production" }

[context.branch-deploy]
  environment = { NODE_ENV = "production", NODE_VERSION = "16.0.0", JEKYLL_ENV = "production"  }
	
[context.deploy-preview]
  environment = { NODE_ENV = "production", NODE_VERSION = "16.0.0", JEKYLL_ENV = "production"  }
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; style-src 'self' https://*.cloudfront.net/ https://*.typography.com https://*.netlify.app/; font-src 'self' https://*.cloudfront.net/ https://*.typography.com https://*.netlify.app/ data:;"